@host=http://pospal.jimtech.solutions:5000/

### ? CUSTOMER API TESTS

### ! Create Customer
POST {{host}}/customers
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john.doe@example.com",
  "phone": "123-456-7890"
}

### ! Read All Customers
GET {{host}}/customers
Content-Type: application/json


### ! Read Single Customer
GET {{host}}/customers/2
Content-Type: application/json


### ! Update a Customer
PUT {{host}}/customers/2
Content-Type: application/json

{
  "name": "Jane Doe",
  "email": "jane.doe@example.com",
  "phone": "098-765-4321"
}

### ! Delete a Customer
DELETE {{host}}/customers/2
Content-Type: application/json

