@host=http://127.0.0.1:5000

# ? PRODUCTS API TESTS

### ! Insert Products
POST {{host}}/products
Content-Type: application/json

{
  "name": "Product 1",
  "price": 30,
  "category": "drinks",
  "stock_quantity": 5
}

### ! Read All Products
GET {{host}}/products
Content-Type: application/json

### ! Read Single Product
GET {{host}}/products/2
Content-Type: application/json

### ! Update a Product
PUT {{host}}/products/2
Content-Type: application/json

{
  "name": "Product 2",
  "price": 30,
  "category": "test",
  "stock_quantity": 5
}

### ! Delete a PRODUCT
DELETE {{host}}/products/4
Content-Type: application/json
