@host=http://pospal.jimtech.solutions:5000/

### ? CUSTOMER API TESTS

### ! Create Suppliers
POST {{host}}/suppliers
Content-Type: application/json

{
  "name": "Supplier 1",
  "contact_name": "Contact 1",
  "phone": "111-222-3333",
  "address": "123 Supplier Street"
}


### ! Read All Supplierss
GET {{host}}/suppliers
Content-Type: application/json



### ! Read Single Suppliers
GET {{host}}/suppliers/1
Content-Type: application/json


### ! Update a Suppliers
PUT {{host}}/suppliers/1
Content-Type: application/json

{
  "name": "Supplier Updated",
  "contact_name": "Contact Updated",
  "phone": "999-888-7777",
  "address": "321 New Supplier Avenue"
}

### ! Delete a Suppliers
DELETE {{host}}/suppliers/1
Content-Type: application/json
